"""
monitor_manager.py
==================
Manages the lifecycle of monitor windows — both standalone subprocess windows
and in-process DPG windows.

Subprocess monitors (original behaviour)
    Each monitor window is a separate OS process (monitor_window.py) with its
    own DearPyGui viewport and its own Socket.IO connection.

In-process monitors (new)
    When a ``MonitorBus`` is provided AND ``set_inprocess_mode(True)`` has been
    called, ``open_monitor()`` creates an ``InProcessMonitor`` (a DPG window
    inside the main editor viewport) that receives data via the bus instead of
    a dedicated Socket.IO connection.
    In-process monitors are updated on the DPG main thread through a recurring
    frame callback set up by ``start_periodic_tasks()``.

    In direct probe mode (InProcessBackend with monitor_bus), MonitorManager
    also manages MonitorProbeObj lifecycle:
      - ``_open_inprocess_monitor`` calls ``backend.attach_probe()`` after
        creating the window so data starts flowing immediately if the simulation
        is already running.
      - ``close_monitor`` calls ``backend.detach_probe()`` to disable the probe.
      - ``_refresh_inprocess_monitor_bindings`` detaches the old probe and
        attaches a new one when the server-output name is remapped.

Key additions over the first subprocess-based version:
  - The display-server URL / port is discovered at simulation start time by
    scanning specula's stdout.  Monitors opened before the port is known are
    queued as *pending* and launched as soon as the URL arrives.
  - A background reaper thread harvests subprocesses that have exited.
  - Optional ``MonitorBus`` enables in-process (DPG-native) monitor windows.

Changes vs. previous version
-----------------------------
* ``set_session_id()`` stores the session_id generated by SimulationControl.
  It is written into the coordination file and passed as ``--session-id`` to
  every spawned subprocess monitor so old monitors stop reconnecting when a
  new run starts (Issue 9).
* ``open_monitor`` raises a visible ValueError (rather than silently using a
  synthetic fallback name) when the server output name cannot be resolved.
  The monitor is queued as pending so it will be retried when params arrive.
* ``_open_inprocess_monitor`` passes the session_id to the InProcessMonitor
  for future diagnostics.
* ``on_server_params()`` now short-circuits for direct backends (InProcessBackend
  with monitor_bus) to prevent Socket.IO rebinding logic from corrupting probe-
  based monitor subscriptions.
"""

import json
import os
import subprocess
import sys
import threading
import time
import traceback

import dearpygui.dearpygui as dpg

from inprocess_monitor import InProcessMonitor

_SYNTHETIC_SERVER_OUTPUT_PREFIX = "auto_"


def _is_direct_backend(backend) -> bool:
    try:
        from simulation_backend import InProcessBackend
        return isinstance(backend, InProcessBackend) and backend._monitor_bus is not None
    except Exception:
        return False


class MonitorManager:
    """Manages monitor windows (subprocess and in-process)."""

    def __init__(self, sio_client, graph, monitor_bus=None, debug: bool = True):
        self.sio_client  = sio_client
        self.graph       = graph
        self.debug       = debug
        self._monitor_bus = monitor_bus
        self._use_inprocess: bool  = False
        self._backend              = None
        self._session_id: str      = ""   # set by simulation_control (Issue 9)

        self.active_monitors: dict  = {}
        self._lock = threading.Lock()
        self._inprocess_monitors: dict[str, InProcessMonitor] = {}
        self._pending_monitors: list = []
        self._server_url: str | None = None

        self._server_url_file: str = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "specula_studio_server.json",
        )

        self._reaper_stop   = threading.Event()
        self._reaper_thread = threading.Thread(
            target=self._reaper_loop, daemon=True
        )
        self._reaper_thread.start()

    # ── Mode / backend / session control ──────────────────────────────────────

    def set_inprocess_mode(self, enabled: bool) -> None:
        self._use_inprocess = enabled
        self._log(f"Monitor mode: {'in-process' if enabled else 'subprocess'}")

    def set_backend(self, backend) -> None:
        self._backend = backend
        self._log(
            f"Backend reference {'set' if backend is not None else 'cleared'}: "
            f"{type(backend).__name__ if backend else 'None'}"
        )

    def set_session_id(self, session_id: str) -> None:
        """Store the session_id for the current simulation run (Issue 9)."""
        self._session_id = session_id
        self._log(f"Session ID updated: {session_id}")

    # ── Logging ──────────────────────────────────────────────────────────[...]

    def _log(self, msg: str):
        if self.debug:
            print(f"[MONITOR_MGR] {msg}")

    # ── Server-event stubs ────────────────────────────────────────────────────

    def on_server_connect(self):    pass
    def on_server_disconnect(self): pass
    def on_server_connect_error(self, data): pass
    def on_data_update(self, name: str, raw_data): pass

    def on_server_params(self, data: dict):
        # FIX: SHORT-CIRCUIT for direct backends (in-process with monitor_bus).
        # In direct mode, monitors are bound to probe topics (node_name.output_name),
        # NOT Socket.IO-mapped topics. Rebinding via Socket.IO mapping will corrupt
        # the subscriptions and cause probes to fail silently.
        if _is_direct_backend(self._backend):
            self._log(
                "on_server_params: skipping Socket.IO rebinding for direct backend "
                "(probe topics are authoritative)"
            )
            return

        if not self._use_inprocess:
            return
        self._flush_pending_monitors()
        self._refresh_inprocess_monitor_bindings()

    def _safe_update_monitor_status(self, monitor_id: str, status: str): pass

    # ── Public query helpers ──────────────────────────────────────────────────

    def is_monitor_open(self, node_uuid: str, output_name: str) -> bool:
        with self._lock:
            for info in self.active_monitors.values():
                if (
                    info.get("node_uuid") == node_uuid
                    and info.get("output_name") == output_name
                    and info["process"].poll() is None
                ):
                    return True
        for m in self._inprocess_monitors.values():
            if m.node_uuid == node_uuid and m.output_name == output_name and m.is_open:
                return True
        return False

    def find_monitor_id(self, node_uuid: str, output_name: str) -> str | None:
        with self._lock:
            for mid, info in self.active_monitors.items():
                if (
                    info.get("node_uuid") == node_uuid
                    and info.get("output_name") == output_name
                    and info["process"].poll() is None
                ):
                    return mid
        for mid, m in self._inprocess_monitors.items():
            if m.node_uuid == node_uuid and m.output_name == output_name and m.is_open:
                return mid
        return None

    # ── Display-server URL notification ───────────────────────────────────────

    def on_display_server_ready(self, url: str):
        self._log(f"Display server ready at {url}")
        old_url = self._server_url
        self._server_url = url

        if old_url != url:
            with self._lock:
                stale = [
                    (mid, info)
                    for mid, info in self.active_monitors.items()
                    if info.get("server_url") != url and info["process"].poll() is None
                ]
            for mid, info in stale:
                self._log(f"Restarting monitor {mid} with new URL {url}")
                try:
                    info["process"].terminate()
                except Exception:
                    pass
                self.open_monitor(None, None, (info["node_uuid"], info["output_name"]))
                with self._lock:
                    self.active_monitors.pop(mid, None)

        self._flush_pending_monitors()

    def _flush_pending_monitors(self) -> None:
        pending = list(self._pending_monitors)
        self._pending_monitors.clear()
        for (s, a, ud) in pending:
            self._log(f"Flushing pending monitor for {ud}")
            self.open_monitor(s, a, ud)

    # ── Open / close ──────────────────────────────────────────────────────────
    def open_monitor(self, sender, app_data, user_data):
        """Open a monitor for the specified node output.
        
        FIX: In direct mode, use direct probe topic (node_name.output_name).
        In Socket.IO mode, resolve server_output_name via DisplayServer.
        """
        node_uuid, output_name = user_data
        
        if node_uuid not in self.graph.nodes:
            self._log(f"Node {node_uuid} not found")
            return

        node_data = self.graph.nodes.get(node_uuid, {})
        node_name = node_data.get("name", node_uuid)

        # ── Direct in-process mode path ────────────────────────────────────────
        if self._use_inprocess:
            # In direct mode, use the probe topic format directly:
            # no Socket.IO resolution needed
            server_output_name = f"{node_name}.{output_name}"
            
            self._open_inprocess_monitor(
                node_uuid, node_name, output_name, server_output_name
            )
            return

        # ── Subprocess/Socket.IO path ──────────────────────────────────────────
        try:
            server_output_name = self.sio_client.get_server_output_name(
                node_uuid, output_name, self.graph.nodes
            )
        except ValueError as e:
            self._log(
                f"Cannot resolve server output name: {e}. "
                f"Queueing monitor for {node_name}.{output_name}"
            )
            self._pending_monitors.append((sender, app_data, user_data))
            return

        node_type = node_data.get("type", "Unknown")

        if self._server_url:
            server_url = self._server_url
        elif self.sio_client.connected:
            server_url = self.sio_client.server_url
        else:
            self._log(
                f"Display-server URL not yet known; queueing monitor for "
                f"{node_name}.{output_name}"
            )
            self._pending_monitors.append((sender, app_data, user_data))
            return

        with self._lock:
            for info in list(self.active_monitors.values()):
                if (
                    info["node_uuid"]   == node_uuid
                    and info["output_name"] == output_name
                    and info["process"].poll() is None
                ):
                    self._log(f"Monitor already open for {node_name}.{output_name}")
                    return

        script = os.path.join(os.path.dirname(os.path.abspath(__file__)), "monitor_window.py")
        cmd = [
            sys.executable, script,
            "--server-output-name", server_output_name,
            "--node-name",          node_name,
            "--output-name",        output_name,
            "--server-url-file",    self._server_url_file,
            "--server-url",         server_url,
        ]
        # Pass session_id so the monitor can validate the coordination file (Issue 9)
        if self._session_id:
            cmd += ["--session-id", self._session_id]

        self._log(f"Spawning monitor: {node_name}.{output_name} → {server_output_name} @ {server_url}")

        try:
            process = subprocess.Popen(cmd, cwd=os.path.dirname(script))
        except Exception as e:
            self._log(f"Failed to spawn monitor process: {e}")
            traceback.print_exc()
            return

        monitor_id = f"{node_uuid}_{output_name}_{int(time.time() * 1000)}"
        with self._lock:
            self.active_monitors[monitor_id] = {
                "process":            process,
                "node_uuid":          node_uuid,
                "output_name":        output_name,
                "server_output_name": server_output_name,
                "node_name":          node_name,
                "node_type":          node_type,
                "server_url":         server_url,
                "session_id":         self._session_id,
                "started_at":         time.time(),
            }    

    # ── In-process monitor helpers ─────────────────────────────────────────────

    def _open_inprocess_monitor(
        self,
        node_uuid: str,
        node_name: str,
        output_name: str,
        server_output_name: str,
    ) -> None:
        for monitor in self._inprocess_monitors.values():
            if (
                monitor.node_uuid   == node_uuid
                and monitor.output_name == output_name
                and monitor.is_open
            ):
                self._log(f"In-process monitor already open for {node_name}.{output_name}")
                monitor.focus()
                return

        monitor_id = f"{node_uuid}_{output_name}_{int(time.time() * 1000)}"
        monitor = InProcessMonitor(
            monitor_id=monitor_id,
            node_uuid=node_uuid,
            node_name=node_name,
            output_name=output_name,
            server_output_name=server_output_name,
            monitor_bus=self._monitor_bus,
            is_direct_mode=_is_direct_backend(self._backend),  # FIX: pass direct mode flag
        )
        monitor.open()
        self._inprocess_monitors[monitor_id] = monitor

        if _is_direct_backend(self._backend):
            probe = self._backend.attach_probe(server_output_name, self._monitor_bus)
            if probe is not None:
                monitor._probe = probe
                self._log(f"Probe attached for '{server_output_name}'")
            else:
                self._log(
                    f"No probe yet for '{server_output_name}' "
                    "— will be injected when simulation starts"
                )
        else:
            try:
                self.sio_client.subscribe(server_output_name)
            except Exception as e:
                self._log(f"Warning: could not subscribe to '{server_output_name}': {e}")

        self._log(f"In-process monitor {monitor_id} opened for {server_output_name}")


    def close_monitor(self, monitor_id: str, from_window_close: bool = False):
        with self._lock:
            info = self.active_monitors.pop(monitor_id, None)
        if info is not None:
            proc = info["process"]
            if proc.poll() is None:
                try:
                    proc.terminate()
                    threading.Thread(
                        target=self._force_kill_after, args=(proc, 3.0), daemon=True
                    ).start()
                except Exception as e:
                    self._log(f"Error terminating: {e}")
            return

        monitor = self._inprocess_monitors.pop(monitor_id, None)
        if monitor is not None:
            if _is_direct_backend(self._backend):
                if monitor._probe is not None:
                    self._backend.detach_probe(monitor._probe)
            else:
                still_watching = any(
                    m.server_output_name == monitor.server_output_name
                    for m in self._inprocess_monitors.values()
                )
                if not still_watching:
                    try:
                        self.sio_client.unsubscribe(monitor.server_output_name)
                    except Exception as e:
                        self._log(f"Warning: could not unsubscribe: {e}")
            monitor.close()

    def _refresh_inprocess_monitor_bindings(self) -> None:
        """Refresh Socket.IO monitor bindings (socket-based in-process mode only).
        
        FIX: This is called only for non-direct backends. Direct backends have
        fixed probe topics and should NEVER reach this code (gated in on_server_params).
        """
        output_to_monitor_ids: dict[str, list[str]] = {}
        for mid, monitor in self._inprocess_monitors.items():
            output_to_monitor_ids.setdefault(monitor.server_output_name, []).append(mid)

        for mid, monitor in list(self._inprocess_monitors.items()):
            try:
                new_output = self.sio_client.get_server_output_name(
                    monitor.node_uuid, monitor.output_name, self.graph.nodes
                )
            except ValueError as e:
                self._log(f"Could not refresh monitor binding for {mid}: {e}")
                continue

            if not new_output or new_output == monitor.server_output_name:
                continue

            old_output = monitor.server_output_name
            changed    = monitor.retarget_server_output(new_output)
            if not changed:
                continue

            if _is_direct_backend(self._backend):
                # Defensive: this should never happen after on_server_params fix,
                # but if it does, log and skip to prevent corruption.
                self._log(
                    f"WARNING: _refresh_inprocess_monitor_bindings reached direct backend "
                    f"for monitor {mid}. Skipping retarget to prevent probe corruption."
                )
                continue

            try:
                self.sio_client.subscribe(new_output)
            except Exception as e:
                self._log(f"Warning: could not subscribe to '{new_output}': {e}")

            old_watchers = output_to_monitor_ids.get(old_output, [])
            if mid in old_watchers:
                old_watchers.remove(mid)
            if not old_watchers:
                try:
                    self.sio_client.unsubscribe(old_output)
                except Exception as e:
                    self._log(f"Warning: could not unsubscribe '{old_output}': {e}")

            self._log(f"Retargeted monitor {mid}: {old_output} → {new_output}")

    @staticmethod
    def _force_kill_after(proc: subprocess.Popen, timeout: float):
        deadline = time.time() + timeout
        while time.time() < deadline:
            if proc.poll() is not None:
                return
            time.sleep(0.1)
        try:
            proc.kill()
        except Exception:
            pass

    # ── Background reaper ──────────────────────────────────────────────────────

    def _reaper_loop(self):
        while not self._reaper_stop.is_set():
            time.sleep(2.0)
            try:
                dead = []
                with self._lock:
                    for mid, info in self.active_monitors.items():
                        if info["process"].poll() is not None:
                            dead.append(mid)
                for mid in dead:
                    with self._lock:
                        info = self.active_monitors.pop(mid, None)
                    if info:
                        self._log(f"Reaped exited monitor {mid} (rc={info['process'].returncode})")
            except Exception as e:
                self._log(f"Reaper error: {e}")

    # ── Ticking ──────────────────────────────────────────────────────────[...]

    def _find_and_close_monitor(self, monitor_info):
        node_uuid, output_name = monitor_info
        with self._lock:
            candidates = [
                mid for mid, info in self.active_monitors.items()
                if info["node_uuid"] == node_uuid and info["output_name"] == output_name
            ]
        for mid in candidates:
            self.close_monitor(mid)
        for mid, monitor in list(self._inprocess_monitors.items()):
            if monitor.node_uuid == node_uuid and monitor.output_name == output_name:
                self.close_monitor(mid)

    def after_dpg_init(self):
        self._log("Ready")

    def start_periodic_tasks(self):
        self._log("start_periodic_tasks called (ticking via main render loop)")

    def _inprocess_tick_direct(self) -> None:
        """Drain and render all in-process monitors every frame.
        
        FIX: Add diagnostic logging to verify data is flowing through the bus.
        """
        if not self._inprocess_monitors:
            return
        
        # Diagnostic: log subscribed topics and push counts periodically
        if hasattr(self, '_tick_count'):
            self._tick_count += 1
        else:
            self._tick_count = 0
        
        if self._tick_count % 300 == 0:  # Log every ~5 seconds at 60 FPS
            subscribed = self._monitor_bus.all_subscribed_outputs()
            push_counts = self._monitor_bus.push_counts()
            drop_counts = self._monitor_bus.drop_counts()
            self._log(
                f"[DIAGNOSTIC] Subscribed topics: {subscribed} | "
                f"Push counts: {push_counts} | Drop counts: {drop_counts}"
            )
            for mid, mon in self._inprocess_monitors.items():
                self._log(
                    f"[DIAGNOSTIC] Monitor {mid}: "
                    f"topic='{mon.server_output_name}' is_open={mon.is_open} "
                    f"queue_size={mon._data_queue.qsize()}"
                )
        
        dead = []
        for mid, monitor in list(self._inprocess_monitors.items()):
            try:
                still_alive = monitor.render_frame()
            except Exception as exc:
                self._log(f"In-process monitor tick error ({mid}): {exc}")
                traceback.print_exc()
                still_alive = False
            if not still_alive:
                dead.append(mid)
        for mid in dead:
            self._inprocess_monitors.pop(mid, None)
            self._log(f"In-process monitor {mid} closed")

    def cleanup(self):
        self._reaper_stop.set()
        with self._lock:
            monitor_ids = list(self.active_monitors.keys())
        for mid in monitor_ids:
            self.close_monitor(mid)
        for mid in list(self._inprocess_monitors.keys()):
            self.close_monitor(mid)
        self._log("All monitors terminated")